import { useState } from 'react';
import { useDiagramStore } from '../state/diagram-store';
import { ExportButton } from './ExportButton';
import { SaveStatus } from './SaveStatus';

export function DiagramToolbar() {
  const [name, setName] = useState(''); const [componentName, setComponentName] = useState(''); const [source, setSource] = useState(''); const [target, setTarget] = useState(''); const [label, setLabel] = useState(''); const [direction, setDirection] = useState<'directed' | 'undirected'>('directed');
  const document = useDiagramStore(state => state.document); const create = useDiagramStore(state => state.create); const addComponent = useDiagramStore(state => state.addComponent); const addRelationship = useDiagramStore(state => state.addRelationship);
  return <div className="editor-toolbar"><div className="toolbar-heading"><div><span className="eyebrow">Canvas controls</span><h2>{document ? 'Build your map' : 'Start with a name'}</h2></div><div className="toolbar-actions"><SaveStatus />{document && <ExportButton />}</div></div>{!document ? <section className="create-row"><label htmlFor="diagram-name">Diagram name</label><div className="control-row"><input id="diagram-name" value={name} onChange={event => setName(event.target.value)} placeholder="e.g. Payments platform" /><button className="primary-pill" onClick={() => void create(name)} disabled={!name.trim()}>Create diagram</button></div></section> : <div className="control-grid"><section className="control-card"><span className="card-kicker">01 · Component</span><label htmlFor="component-name">Name your next building block</label><div className="control-row"><input id="component-name" value={componentName} onChange={event => setComponentName(event.target.value)} placeholder="e.g. API gateway" /><button className="primary-pill" onClick={() => { addComponent(componentName); setComponentName(''); }} disabled={!componentName.trim()}>Add</button></div></section><section className="control-card"><span className="card-kicker">02 · Relationship</span><label htmlFor="relationship-source">Connect two components</label><div className="control-row relationship-row"><select id="relationship-source" value={source} onChange={event => setSource(event.target.value)}><option value="">From…</option>{document.components.map(component => <option key={component.id} value={component.id}>{component.name}</option>)}</select><select aria-label="Relationship target" value={target} onChange={event => setTarget(event.target.value)}><option value="">To…</option>{document.components.map(component => <option key={component.id} value={component.id}>{component.name}</option>)}</select><input aria-label="Relationship label" value={label} onChange={event => setLabel(event.target.value)} placeholder="Label" /><select aria-label="Relationship direction" value={direction} onChange={event => setDirection(event.target.value as 'directed' | 'undirected')}><option value="directed">Directed</option><option value="undirected">Undirected</option></select><button className="primary-pill" onClick={() => { addRelationship(source, target, label, direction); setLabel(''); }} disabled={!source || !target || source === target}>Connect</button></div></section></div>}</div>;
}
