import { describe, expect, it } from 'vitest';
import { buildApp } from '../src/api/app';
import { DiagramRepository } from '../src/persistence/diagram-repository';
import { DiagramService } from '../src/services/diagram-service';
import { AdrRepository } from '../src/persistence/adr-repository';
import { completeAdrPayload } from './fixtures';
import type { DiagramDocument } from '../../shared/src/index';
const document: DiagramDocument = { id: 'diagram', name: 'System', status: 'active', createdAt: 'now', updatedAt: 'now', trashedAt: null, components: [{ id: 'api', diagramId: 'diagram', name: 'API', description: null, type: null, position: { x: 0, y: 0 }, createdAt: 'now', updatedAt: 'now' }, { id: 'db', diagramId: 'diagram', name: 'DB', description: null, type: null, position: { x: 1, y: 1 }, createdAt: 'now', updatedAt: 'now' }], relationships: [{ id: 'uses', diagramId: 'diagram', sourceComponentId: 'api', targetComponentId: 'db', direction: 'directed', label: null, createdAt: 'now', updatedAt: 'now' }], groups: [] };
describe('recovery service', () => {
  it('counts dependencies and rejects removal while relationships are attached', () => { const repository = new DiagramRepository(); repository.create(document); const service = new DiagramService(repository); expect(service.dependencyCount('diagram', 'api')).toBe(1); expect(() => service.removeComponent('diagram', 'api')).toThrow(/Remove the relationships first/); expect(repository.get('diagram')?.components.map(c => c.id)).toEqual(['api', 'db']); });
  it('removes an unconnected component without changing relationships', () => { const repository = new DiagramRepository(); repository.create({ ...document, components: [document.components[0]] , relationships: [] }); const service = new DiagramService(repository); const result = service.removeComponent('diagram', 'api'); expect(result.relationshipCount).toBe(0); expect(result.document.components).toEqual([]); expect(result.document.relationships).toEqual([]); });
  it('reports missing diagrams and components', () => { const service = new DiagramService(new DiagramRepository()); expect(() => service.dependencyCount('missing', 'api')).toThrow(/Diagram not found/); });
  it('rechecks dependencies when a stale preflight is followed by removal', () => { const repository = new DiagramRepository(); const unconnected = { ...document, relationships: [] }; repository.create(unconnected); const service = new DiagramService(repository); expect(service.dependencyCount('diagram', 'api')).toBe(0); repository.replace(document); expect(() => service.removeComponent('diagram', 'api')).toThrow(/1 dependent relationship/); expect(repository.get('diagram')?.components).toHaveLength(2); });
  it('blocks deletion when an ADR links the component and leaves the diagram unchanged', () => { const componentId = '00000000-0000-0000-0000-000000000098'; const repository = new DiagramRepository(); repository.create({ ...document, relationships: [], components: [{ ...document.components[0], id: componentId }] }); const adrs = new AdrRepository(); const adr = adrs.create('00000000-0000-0000-0000-000000000099', completeAdrPayload); adrs.replaceLinks(adr.id, [componentId]); const service = new DiagramService(repository, adrs); expect(() => service.removeComponent('diagram', componentId)).toThrow(/linked to one or more ADRs/); expect(repository.get('diagram')?.components.map(component => component.id)).toEqual([componentId]); });
  it('moves a diagram to trash and restores its stable content', () => { const repository = new DiagramRepository(); repository.create(document); const service = new DiagramService(repository); service.trash('diagram'); expect(repository.list()).toEqual([]); expect(repository.listTrash()[0].id).toBe('diagram'); const restored = service.restore('diagram'); expect(restored.status).toBe('active'); expect(restored.components[0].id).toBe('api'); expect(restored.relationships[0].id).toBe('uses'); });
  it('preserves the original creation date through edit, trash, and restore', () => { const repository = new DiagramRepository(); repository.create(document); const service = new DiagramService(repository); const edited = repository.replace({ ...document, name: 'Renamed', createdAt: 'changed-by-client' }); expect(edited?.createdAt).toBe(document.createdAt); service.trash('diagram'); expect(repository.listTrash()[0].createdAt).toBe(document.createdAt); expect(service.restore('diagram').createdAt).toBe(document.createdAt); });
  it('returns createdAt in trash summaries and preserves it after restore', async () => { const repository = new DiagramRepository(); repository.create(document); const app = buildApp(repository); await app.ready();
    expect((await app.inject({ method: 'DELETE', url: '/diagrams/diagram' })).statusCode).toBe(204);
    const trash = await app.inject({ method: 'GET', url: '/diagrams/trash' });
    expect(trash.json()).toEqual([expect.objectContaining({ id: 'diagram', status: 'trashed', createdAt: document.createdAt })]);
    expect((await app.inject({ method: 'POST', url: '/diagrams/diagram/restore' })).json()).toMatchObject({ id: 'diagram', status: 'active', createdAt: document.createdAt });
    await app.close();
  });
  it('returns not found for a missing deletion target and leaves all active diagrams unchanged', async () => { const repository = new DiagramRepository(); repository.create(document); const app = buildApp(repository); await app.ready();
    const response = await app.inject({ method: 'DELETE', url: '/diagrams/missing' });
    expect(response.statusCode).toBe(404);
    expect(repository.list().map(item => item.id)).toEqual(['diagram']);
    await app.close();
  });
  it('targets duplicate names by UUID and restores the complete document without changing identities', async () => { const repository = new DiagramRepository(); const duplicate = { ...document, id: 'diagram-duplicate', components: document.components.map(component => ({ ...component, diagramId: 'diagram-duplicate' })) , relationships: document.relationships.map(relationship => ({ ...relationship, diagramId: 'diagram-duplicate', sourceComponentId: 'api', targetComponentId: 'db' })) }; repository.create(document); repository.create(duplicate); const app = buildApp(repository); await app.ready();
    expect((await app.inject({ method: 'DELETE', url: '/diagrams/diagram-duplicate' })).statusCode).toBe(204);
    expect(repository.list().map(item => item.id)).toEqual(['diagram']);
    const restored = await app.inject({ method: 'POST', url: '/diagrams/diagram-duplicate/restore' });
    expect(restored.statusCode).toBe(200);
    expect(restored.json()).toMatchObject({ id: 'diagram-duplicate', createdAt: document.createdAt, components: expect.arrayContaining([expect.objectContaining({ id: 'api' })]), relationships: expect.arrayContaining([expect.objectContaining({ id: 'uses' })]) });
    await app.close();
  });
});
