import { describe, expect, it } from 'vitest';
import { DiagramRepository } from '../src/persistence/diagram-repository';
import { DiagramService } from '../src/services/diagram-service';
import type { DiagramDocument } from '../../shared/src/index';
const document: DiagramDocument = { id: 'diagram', name: 'System', status: 'active', createdAt: 'now', updatedAt: 'now', trashedAt: null, components: [{ id: 'api', diagramId: 'diagram', name: 'API', description: null, type: null, position: { x: 0, y: 0 }, createdAt: 'now', updatedAt: 'now' }, { id: 'db', diagramId: 'diagram', name: 'DB', description: null, type: null, position: { x: 1, y: 1 }, createdAt: 'now', updatedAt: 'now' }], relationships: [{ id: 'uses', diagramId: 'diagram', sourceComponentId: 'api', targetComponentId: 'db', direction: 'directed', label: null, createdAt: 'now', updatedAt: 'now' }] };
describe('recovery service', () => {
  it('counts dependencies and rejects removal while relationships are attached', () => { const repository = new DiagramRepository(); repository.create(document); const service = new DiagramService(repository); expect(service.dependencyCount('diagram', 'api')).toBe(1); expect(() => service.removeComponent('diagram', 'api')).toThrow(/Remove the relationships first/); expect(repository.get('diagram')?.components.map(c => c.id)).toEqual(['api', 'db']); });
  it('removes an unconnected component without changing relationships', () => { const repository = new DiagramRepository(); repository.create({ ...document, components: [document.components[0]] , relationships: [] }); const service = new DiagramService(repository); const result = service.removeComponent('diagram', 'api'); expect(result.relationshipCount).toBe(0); expect(result.document.components).toEqual([]); expect(result.document.relationships).toEqual([]); });
  it('reports missing diagrams and components', () => { const service = new DiagramService(new DiagramRepository()); expect(() => service.dependencyCount('missing', 'api')).toThrow(/Diagram not found/); });
  it('rechecks dependencies when a stale preflight is followed by removal', () => { const repository = new DiagramRepository(); const unconnected = { ...document, relationships: [] }; repository.create(unconnected); const service = new DiagramService(repository); expect(service.dependencyCount('diagram', 'api')).toBe(0); repository.replace(document); expect(() => service.removeComponent('diagram', 'api')).toThrow(/1 dependent relationship/); expect(repository.get('diagram')?.components).toHaveLength(2); });
  it('moves a diagram to trash and restores its stable content', () => { const repository = new DiagramRepository(); repository.create(document); const service = new DiagramService(repository); service.trash('diagram'); expect(repository.list()).toEqual([]); expect(repository.listTrash()[0].id).toBe('diagram'); const restored = service.restore('diagram'); expect(restored.status).toBe('active'); expect(restored.components[0].id).toBe('api'); expect(restored.relationships[0].id).toBe('uses'); });
});
