import { containerAvailabilitySchema, diagramDocumentSchema, diagramSummaryListSchema, type ContainerAvailability, type DiagramDocument, type DiagramSummary } from '../../../shared/src/index';
export class DiagramApiError extends Error { constructor(message: string, readonly status: number, readonly details: Record<string, unknown> = {}) { super(message); this.name = 'DiagramApiError'; } }
export type ComponentRemovalResult = { document: DiagramDocument; relationshipCount: number };
export type ComponentRemovalConflict = { message: string; componentId: string; relationshipCount: number; groupIds: string[]; blockers?: unknown[] };
const json = async (response: Response) => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new DiagramApiError(body.message ?? 'Request failed', response.status, body); return body; };
const summaries = async (response: Response): Promise<DiagramSummary[]> => diagramSummaryListSchema.parse(await json(response));
export const diagramClient = {
  list: () => fetch('/api/diagrams').then(summaries), create: async (name: string) => diagramDocumentSchema.parse(await json(await fetch('/api/diagrams', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name }) }))) as DiagramDocument, get: async (id: string) => diagramDocumentSchema.parse(await json(await fetch(`/api/diagrams/${id}`))) as DiagramDocument, save: async (d: DiagramDocument) => diagramDocumentSchema.parse(await json(await fetch(`/api/diagrams/${d.id}`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(d) }))) as DiagramDocument,
  containerAvailability: async (diagramId: string, componentId: string): Promise<ContainerAvailability> => containerAvailabilitySchema.parse(await json(await fetch(`/api/diagrams/${diagramId}/components/${componentId}/container-diagram`))),
  createOrOpenContainerDiagram: async (diagramId: string, componentId: string): Promise<DiagramDocument> => diagramDocumentSchema.parse(await json(await fetch(`/api/diagrams/${diagramId}/components/${componentId}/container-diagram`, { method: 'POST' }))) as DiagramDocument,
  dependencyCount: (diagramId: string, componentId: string) => fetch(`/api/diagrams/${diagramId}/components/${componentId}/dependencies`).then(json) as Promise<{ relationshipCount: number }>, removeComponent: (diagramId: string, componentId: string) => fetch(`/api/diagrams/${diagramId}/components/${componentId}`, { method: 'DELETE' }).then(json) as Promise<ComponentRemovalResult>, removeRelationship: (diagramId: string, relationshipId: string) => fetch(`/api/diagrams/${diagramId}/relationships/${relationshipId}`, { method: 'DELETE' }).then(json) as Promise<{ document: DiagramDocument }>, trash: async (id: string): Promise<void> => { const response = await fetch(`/api/diagrams/${id}`, { method: 'DELETE' }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new DiagramApiError(body.message ?? 'Could not move diagram to trash', response.status, body); } }, listTrash: () => fetch('/api/diagrams/trash').then(summaries), restore: (id: string) => fetch(`/api/diagrams/${id}/restore`, { method: 'POST' }).then(json) as Promise<DiagramDocument>
};
