import {describe,expect,it} from 'vitest';
import {Position} from '@xyflow/react';
import {toReactFlow,fromReactFlow,nearestHandle} from '../src/adapters/react-flow/diagram-adapter';
import {relationshipPath} from '../src/components/RelationshipEdge';

const d:any={id:'d',name:'x',status:'active',createdAt:'n',updatedAt:'n',trashedAt:null,components:[{id:'a',diagramId:'d',name:'API',position:{x:1,y:2}},{id:'b',diagramId:'d',name:'DB',position:{x:100,y:2}},{id:'c',diagramId:'d',name:'Cache',position:{x:100,y:100}}],relationships:[{id:'r1',diagramId:'d',sourceComponentId:'a',targetComponentId:'b',direction:'directed',label:'one'},{id:'r2',diagramId:'d',sourceComponentId:'b',targetComponentId:'a',direction:'directed',label:'two'}]};
const horizontalRoute=(edge:any)=>edge.source==='a'?relationshipPath({sourceX:0,sourceY:0,targetX:200,targetY:0,sourcePosition:Position.Right,targetPosition:Position.Left,data:edge.data}):relationshipPath({sourceX:200,sourceY:0,targetX:0,targetY:0,sourcePosition:Position.Left,targetPosition:Position.Right,data:edge.data});
const verticalRoute=(edge:any)=>edge.source==='a'?relationshipPath({sourceX:0,sourceY:0,targetX:0,targetY:200,sourcePosition:Position.Bottom,targetPosition:Position.Top,data:edge.data}):relationshipPath({sourceX:0,sourceY:200,targetX:0,targetY:0,sourcePosition:Position.Top,targetPosition:Position.Bottom,data:edge.data});

describe('React Flow adapter',()=>{
  it('round trips IDs and positions',()=>{const visual=toReactFlow(d);expect(visual.nodes[0].id).toBe('a');expect(fromReactFlow(d,[{...visual.nodes[0],position:{x:9,y:8}} as any]).components[0].id).toBe('a');});
  it('selects the nearest directional handles',()=>{expect(nearestHandle({x:0,y:0},{x:100,y:10})).toEqual({source:'right',target:'left'});expect(nearestHandle({x:0,y:0},{x:10,y:100})).toEqual({source:'bottom',target:'top'});});
  it('separates reciprocal and parallel relationships into distinct horizontal paths',()=>{const reciprocal=toReactFlow(d).edges;expect(horizontalRoute(reciprocal[0]).path).not.toBe(horizontalRoute(reciprocal[1]).path);const parallel=toReactFlow({...d,relationships:[d.relationships[0],{...d.relationships[0],id:'r3'}]}).edges;expect(horizontalRoute(parallel[0]).path).not.toBe(horizontalRoute(parallel[1]).path);});
  it('separates reciprocal relationships into distinct vertical paths',()=>{const edges=toReactFlow({...d,components:[{...d.components[0],position:{x:0,y:0}},{...d.components[1],position:{x:0,y:200}}]}).edges;expect(verticalRoute(edges[0]).path).not.toBe(verticalRoute(edges[1]).path);});
  it('assigns distinct fan lanes for horizontal and vertical relationships',()=>{const horizontal=toReactFlow({...d,relationships:[d.relationships[0],{...d.relationships[0],id:'r3',targetComponentId:'c'}]}).edges;expect(horizontal[0].data?.sourceFanOffset).not.toBe(horizontal[1].data?.sourceFanOffset);const vertical=toReactFlow({...d,components:[{...d.components[0],position:{x:0,y:0}},{...d.components[1],position:{x:0,y:100}},{...d.components[2],position:{x:10,y:100}}],relationships:[{...d.relationships[0],targetComponentId:'b'},{...d.relationships[0],id:'r3',targetComponentId:'c'}]}).edges;expect(vertical[0].data?.sourceFanOffset).not.toBe(vertical[1].data?.sourceFanOffset);});
  it('keeps routing stable when relationships are supplied in a different order',()=>{const original=toReactFlow({...d,relationships:[d.relationships[0],{...d.relationships[0],id:'r3'},d.relationships[1]]}).edges;const reordered=toReactFlow({...d,relationships:[d.relationships[1],{...d.relationships[0],id:'r3'},d.relationships[0]]}).edges;expect(Object.fromEntries(original.map(edge=>[edge.id,edge.data]))).toEqual(Object.fromEntries(reordered.map(edge=>[edge.id,edge.data])));});
});
